server:
  port: 8080
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/lin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
logging:
  level:
    com.example.demo.mapper: debug