server:
  port: 8080
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/lin
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    